apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust
    component: master
spec:
  selector:
    app: locust
    component: master
  ports:
  - name: web
    port: 8089
    targetPort: 8089
  - name: master
    port: 5557
    targetPort: 5557
  - name: worker
    port: 5558
    targetPort: 5558

---
apiVersion: v1
kind: Service
metadata:
  name: locust-worker
  labels:
    app: locust
    component: worker
spec:
  selector:
    app: locust
    component: worker
  ports:
  - name: worker
    port: 5557
    targetPort: 5557