# values.yaml
replicaCount: 2

image:
  repository: locustio/locust
  tag: 2.15.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8089

ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "locust.argo.local"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: locust-tls
      hosts:
        - "locust.argo.local"

config:
  locustfile: "locustfile.py"
  targetHost: "http://simple-calculator-frontend.deifops.svc"
  users: 100
  spawnRate: 10
  runTime: "10m"

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi