services:
  frontend:
    image: calculator-frontend
    build:
      context: ./frontend/
    # pull_policy: build
    networks:
      - calc_net
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: calculator-backend
    build:
      context: ./backend
    # pull_policy: build
    networks:
      - calc_net
    environment:
      DEBUG: True
      ALLOWED_ORIGINS: 'http://${DOMAIN_NAME}'
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - calc_net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  calc_net: